# Generated by Django 3.1.1 on 2020-10-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_mail', models.EmailField(max_length=254)),
                ('student_phoneno', models.IntegerField()),
                ('student_address', models.CharField(max_length=50)),
            ],
        ),
    ]
